var navData={
  '1':{
    type:'desc',
    title:"如何使用Evernote"
  },
  '1.1':{
    type:'link',
    title:"随时随地高效工作"
  },
  '1.2':{
    type:'link',
    title:'将Evernote企业版与其他工具结合使用'
  },
  '1.3':{
    type:'link',
    title:'如何从Evernote免费版、标准版或高级版帐户转换为企业版帐户'
  },
  '1.4':{
    type:'link',
    title:'让会议更高效'
  },
  2:{
    type:'desc',
    title:"功能概述",
  },
  '2.1':{
    type:"link",
    title:"功能概述如何将笔记整理至不同的笔记本"
  },
  '2.2':{
    type:'desc',
    title:'视频线上研讨'
  },
  '2.2.1':{
    type:'link',
    title:'视频教程：Evernote入门指南 Windows 版'
  },
  '2.2.2':{
    type:'link',
    title:"视频教程：Evernote入门指南 Mac 版"
  },
  3:{
    type:'desc',
    title:"进阶技巧",
  },
  '3.1':{
    type:'link',
    title:'如何使用Evernote高级搜索语法'
  },
  '3.2':{
    type:'link',
    title:'如何设置 ScanSnap 无线扫描仪，使其能够扫描文档至Evernote'
  },
  '3.3':{
    type:'link',
    title:'Evernote iPhone, iPad 和 iPod Touch 版键盘快捷键'
  },
  '3.4':{
    type:'link',
    title:'如何才能将多条笔记合并为一条'
  },
  4:{
    type:'desc',
    title:"Evernote企业版使用技巧及指南",
  },
  '4.1':{
    type:'link',
    title:'如何扫描名片联系人到Salesforce'
  },
  '4.2':{
    type:'link',
    title:'Evernote企业版常见问题'
  },
  '4.3':{
    type:'link',
    title:'如何升级到Evernote企业版'
  },

  5:{
    type:'desc',
    title:"合作伙伴及应用整合",
  },
  '5.1':{
    type:'link',
    title:'Evernote Outlook版快速入门指南'
  },
  '5.2':{
    type:'link',
    title:'如何使用Microsoft Outlook Clipper 插件将邮件存入Evernote'
  },
  '5.3':{
    type:'link',
    title:'开始使用Evernote（Salesforce版）'
  },
  '5.4':{
    type:'link',
    title:'Evernote（Salesforce版）常见问题'
  }

}
